version: "3.9"
services:
  db:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - data:/var/lib/registry
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  data: