version: "3"

services:
  proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - well_known:/var/www/html:ro
    depends_on:
      - certbot

  certbot:
    image: cert
    volumes:
      - well_known:/var/www/html

volumes:
  well_known:
    external: true